### PR TITLE
g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 changes

### PR DESCRIPTION
**Pull request by jmikedupont2**
This PR is a work in progress, needs to be reformated and also the multiple decls need to be refactored but this is a starting point for people wanting to use a modern gcc. It now linkes for cuda 12

### CODE REVIEW

**Comment by nikkon-dev** [comment]
@jmikedupont2,

Thank you for your engagement with the project. It's important to note that the DCGM build system is designed to function specifically within the build container. This setup includes building all third-party dependencies and placing them in the /opt/cross directory while constructing the dcgmbuild docker image. This process is particularly tied to the versions and headers of Cuda.

Please be aware that we cannot approve changes that disrupt this established scenario.

**Comment by jmikedupont2** [comment]
I just added in the the vendor you can just ignore that but look at the changes for upgrading the compiler because there is the changes needed for the format strings to upgrade your compiler version

**Comment by nikkon-dev** [comment]
I would appreciate it if you could provide more details regarding the changes you require from GCC 11.2, 11.3, or 11.4. The formatting-related changes are difficult to isolate from the pull request, making it challenging to understand your requirements. Please note that we do not use std::format and opt for fmtlib instead. 

The current commits included in this PR make it impossible for us to merge it. If you encounter any issues with the builds, please create individual issues, so we can track efforts and indicate if a PR would be acceptable/desired. However, please bear in mind that we won't accept changes that disable Cuda 10 and 11 in any circumstances or break the containerized build environment.

**Comment by jmikedupont2** [comment]
Here is a cleaner PR that only has the C++ changes.
Note that newrandom.h was not found anywhere.
https://github.com/NVIDIA/DCGM/pull/130

**Comment by jmikedupont2** [comment]
I refactored the cmake changes to its own branch in case someone needs that, marked and closed the pr for the record. Hope that helps someone in the future.

**Pull request closed without merging**
